# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ build-blog ]

jobs:
  build:
    name: Build

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - run: rm -rf blog/_posts
    - uses: actions/checkout@v2
      with:
        repository: leuction/blog
        token: ${{ secrets.LEUCTION_GITHUB_PAT }}
        path: leuction/blog
        persist-credentials: false
    - uses: actions/checkout@v2
      with:
        repository: seraphlive/my-article
        token: ${{ secrets.SERAPHLIVE_GITHUB_PAT }}
        path: seraphlive/my-article
        persist-credentials: false
    - run: mkdir -p blog/_posts
    - run: cp -r leuction/blog/* blog/_posts/
    - run: cp -r seraphlive/my-article/public/* blog/_posts/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Build website
      run: npm run build
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: ./blog/.vuepress/dist
        path: ./blog/.vuepress/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ./blog/.vuepress/dist
          path: ./blog/.vuepress/dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}